apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-nvme
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-nvme-config 
  namespace: local-storage
data:
  storageClassMap: |     
    local-storage-nvme:
       hostDir: /mnt/nvme
       mountDir:  /mnt/nvme
       blockCleanerCommand:
         - "/scripts/shred.sh"
         - "2" 
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: local-volume-nvme-provisioner
  namespace: local-storage
  labels:
    app: local-volume-nvme-provisioner
spec:
  selector:
    matchLabels:
      app: local-volume-nvme-provisioner 
  template:
    metadata:
      labels:
        app: local-volume-nvme-provisioner
    spec:
      serviceAccountName: local-storage-admin
      containers:
        - image: "quay.io/external_storage/local-volume-provisioner:v2.1.0"
          imagePullPolicy: "Always"
          name: provisioner 
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /etc/provisioner/config 
              name: provisioner-config
              readOnly: true             
            - mountPath:  /mnt/nvme
              name: local-storage
              mountPropagation: "HostToContainer" 
      volumes:
        - name: provisioner-config
          configMap:
            name: local-provisioner-nvme-config         
        - name: local-storage
          hostPath:
            path: /mnt/nvme
